version: "3.9"

services:
    database:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - local_network

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        depends_on:
            - database
        ports:
            - "10000:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=jadjer@ya.ru
            - PGADMIN_DEFAULT_PASSWORD=jadjer_for_pgadmin_password
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - local_network
        logging:
            driver: none

    app:
        build:
            context: .
        depends_on:
            - database
        ports:
            - "8000-8009:8000"
        env_file: .env
        networks:
            - local_network

    nginx:
        image: nginx
        restart: always
        depends_on:
            - app
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - local_network
        logging:
            driver: none

networks:
    local_network:
        driver: bridge

volumes:
    postgres_data:
    pgadmin_data:
