"""update event model

Revision ID: 074315a63b56
Revises: 9a20da6ccc1a
Create Date: 2022-06-02 13:20:51.758845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '074315a63b56'
down_revision = '9a20da6ccc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint('events_title_key', 'events', type_='unique')
    op.drop_constraint('events_author_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'posts', ['post_id'], ['id'])
    op.drop_column('events', 'thumbnail')
    op.drop_column('events', 'body')
    op.drop_column('events', 'author_id')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'description')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_author_id_fkey', 'events', 'users', ['author_id'], ['id'])
    op.create_unique_constraint('events_title_key', 'events', ['title'])
    op.drop_column('events', 'post_id')
    # ### end Alembic commands ###
