"""Update user and profile models

Revision ID: 1a9b12cf76dd
Revises: 67e3b446b7a7
Create Date: 2022-06-03 00:27:45.892606

"""
#  Copyright 2022 Pavel Suprunov
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9b12cf76dd'
down_revision = '67e3b446b7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['username'])
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'username')
    # ### end Alembic commands ###
