"""Create user location model

Revision ID: 1f41b1371cc8
Revises: e402e6fda7f2
Create Date: 2022-06-28 14:45:44.069076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f41b1371cc8'
down_revision = 'e402e6fda7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
