"""update vehicle model

Revision ID: 2464f0f661ca
Revises: 915b3ce872fb
Create Date: 2022-05-31 17:52:35.626373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2464f0f661ca'
down_revision = '915b3ce872fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vin', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('registration_plate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'registration_plate')
    op.drop_column('vehicles', 'vin')
    # ### end Alembic commands ###
