"""update vehicle model 2

Revision ID: 3668c5c588a6
Revises: 2464f0f661ca
Create Date: 2022-05-31 17:54:06.054541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3668c5c588a6'
down_revision = '2464f0f661ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vehicles', ['registration_plate'])
    op.create_unique_constraint(None, 'vehicles', ['vin'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_constraint(None, 'vehicles', type_='unique')
    # ### end Alembic commands ###
