"""Create price in service model

Revision ID: 38da37d1a7ac
Revises: a2ede36ef920
Create Date: 2022-06-05 10:30:58.772684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38da37d1a7ac'
down_revision = 'a2ede36ef920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'price')
    # ### end Alembic commands ###
