"""remove relationship from token

Revision ID: 555644b0ff31
Revises: 87a3aa76db63
Create Date: 2022-05-23 13:57:46.984930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555644b0ff31'
down_revision = '87a3aa76db63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
