"""Update api key model

Revision ID: 5840633bbc7a
Revises: 09c21683f59e
Create Date: 2022-06-27 18:20:12.572502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5840633bbc7a'
down_revision = '09c21683f59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('api_key', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'updated_at')
    op.drop_column('api_key', 'created_at')
    # ### end Alembic commands ###
