"""remove relationship from vehicle

Revision ID: 87a3aa76db63
Revises: f30a82a4f733
Create Date: 2022-05-23 13:56:32.490929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a3aa76db63'
down_revision = 'f30a82a4f733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
