"""Change mileage's field type to Integer

Revision ID: 8a5531fc7c02
Revises: 38da37d1a7ac
Create Date: 2022-06-05 13:45:25.358562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5531fc7c02'
down_revision = '38da37d1a7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel', sa.Column('mileage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel', 'mileage')
    # ### end Alembic commands ###
