"""update tables

Revision ID: 9a20da6ccc1a
Revises: 3668c5c588a6
Create Date: 2022-06-01 15:20:47.355276

"""
#  Copyright 2022 Pavel Suprunov
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a20da6ccc1a'
down_revision = '3668c5c588a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'posts', ['title'])
    op.create_unique_constraint(None, 'service_types', ['name'])
    op.add_column('vehicles', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'name')
    op.drop_constraint(None, 'service_types', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.alter_column('posts', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
