"""Update user and profile models

Revision ID: 9cf0a8ab9242
Revises: 0e1b7b3da949
Create Date: 2022-06-08 17:02:34.891462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf0a8ab9242'
down_revision = '0e1b7b3da949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
