"""create profile table

Revision ID: b054b578fc04
Revises: 074315a63b56
Create Date: 2022-06-02 20:13:10.939243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b054b578fc04'
down_revision = '074315a63b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('UNDEFINED', 'MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'age')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', postgresql.ENUM('UNDEFINED', 'MALE', 'FEMALE', name='gender'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
