"""Update remonder date's field

Revision ID: bcd07934a5ec
Revises: 8a5531fc7c02
Create Date: 2022-06-05 14:33:10.003463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcd07934a5ec'
down_revision = '8a5531fc7c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('next_date', sa.Date(), nullable=False))
    op.drop_column('reminder', 'next_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('next_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('reminder', 'next_date')
    # ### end Alembic commands ###
