"""Update models

Revision ID: e402e6fda7f2
Revises: 2b7f5abc23fd
Create Date: 2022-06-27 19:54:12.475086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e402e6fda7f2'
down_revision = '2b7f5abc23fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('profile', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('service_type', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('service_type', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('token', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('vehicle', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('vehicle', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'updated_at')
    op.drop_column('vehicle', 'created_at')
    op.drop_column('token', 'created_at')
    op.drop_column('service_type', 'updated_at')
    op.drop_column('service_type', 'created_at')
    op.drop_column('profile', 'updated_at')
    op.drop_column('profile', 'created_at')
    # ### end Alembic commands ###
