"""Added timestamp to models

Revision ID: f9b6d59b9f76
Revises: 66ebf6c554d4
Create Date: 2022-06-06 11:51:47.572005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9b6d59b9f76'
down_revision = '66ebf6c554d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('comment', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('comment', 'datetime')
    op.add_column('event', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_confirmation', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('event_confirmation', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fuel', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('fuel', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('fuel', 'datetime')
    op.add_column('location', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('location', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reminder', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('reminder', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('service', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('service', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('service', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('service', 'updated_at')
    op.drop_column('service', 'created_at')
    op.drop_column('reminder', 'updated_at')
    op.drop_column('reminder', 'created_at')
    op.drop_column('location', 'updated_at')
    op.drop_column('location', 'created_at')
    op.add_column('fuel', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('fuel', 'updated_at')
    op.drop_column('fuel', 'created_at')
    op.drop_column('event_confirmation', 'updated_at')
    op.drop_column('event_confirmation', 'created_at')
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'created_at')
    op.add_column('comment', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'updated_at')
    op.drop_column('comment', 'created_at')
    # ### end Alembic commands ###
